app.py
from flask import Flask
from views import view_blueprint

app = Flask(__name__)

app.register_blueprint(view_blueprint, url_prefix="/",  static_url_path='/static')

if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0')

views.py
import json
from flask import Blueprint, render_template,redirect, url_for

view_blueprint = Blueprint("view", __name__)

with open("data.json", "r") as file:
    data = json.load(file)

print(data)

@view_blueprint.route("/")
def home():
    return render_template("index.html", data=data)

@view_blueprint.route("/home")
def home1():
    return render_template("index.html", data=data)

@view_blueprint.route("/vacancy")
def vacancy():
    # Assuming you have a route for the form, let's say 'form'
    return redirect(url_for("form"))

# Assuming you have a route for the form, let's say 'form'
@view_blueprint.route("/form")
def form():
    return render_template("form.html")

templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='StyleSheet/index.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Career Connect</title>
</head>
<body>
    {% include 'navbar.html' %}
    
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Career Connect</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='StyleSheet/index.css') }}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="heading-div">
            <h1 class="animated-heading">Career Connect</h1><br>
        </div>
        <img src={{ url_for('static', filename='images/reference.jpeg') }} alt="An Image" loading="lazy">
        <header>
            <h2 class="heading">About Career Connect</h2>
            <ul class="header-list">
                <li>
                    CareerConnect is a Flask-based career website designed to connect job seekers and employers.<br>
                    It provides a platform for users to explore and apply for jobs,<br>
                    and for employers to post vacancies and manage applications.
                </li>

                <li>
                    The website features a search functionality that allows users to filter jobs based on location,<br>
                    job type, and industry. It leverages Flask's lightweight design<br>
                    and extensions to deliver a secure and efficient user experience. 
                </li>

                <li>
                    The project follows best practices in web development, including RESTful routing,<br>
                    session management, and database schema design. CareerConnect is a scalable and secure solution<br>
                    for job search and recruitment needs.
                </li>
            </ul>
        </header>
        <main>
        <h2 class="heading second-heading">Open Positions</h2>
            {% include 'section.html' %}
            
        </main>
        <hr class="hr-footer">
        <footer>
            <aside>&copy;CareerConnect, 2023</aside>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a href="{{ url_for('view.home') }}" class="navbar-brand"><span class="title-word title-word-1">Career</span><span class="title-word title-word-2">Connect</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav3"
        aria-controls="navbarNav3" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav3">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a href="#" class="nav-link active" aria-current="page">Home</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">About</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">Contact</a>
          </li>

          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbar-dropdown-link-2" role="button"
              data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="navbar-dropdown-link-2">
              <li>
                <a href="#" class="dropdown-item">Electronics</a>
              </li>
              <li>
                <a href="#" class="dropdown-item">Embedded Circuits</a>
              </li>
              <li class="dropdown dropend">
                <a href="#" class="dropdown-item dropdown-toggle" id="navbar-dropdown-list-deep-1" role="button"
                  data-bs-toggle="dropdown" aria-expanded="false">
                  Mosaics
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown-link-1">
                  <li>
                    <a href="#" class="dropdown-item">Roman</a>
                  </li>
                  <li>
                    <a href="#" class="dropdown-item">Byzantine</a>
                    <a href="#" class="dropdown-item">Art Nouveau</a>
                  </li>
                </ul>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>

templates/section.html
{% for job in data %}
    <section>
        <div class="flex-div1">
            <h3> {{ data[job]["title"] }} </h3>
            <h4>Location:-<em>{{  data[job]["location"]  }}</em></h4>
            {% if 'salary' in data[job] %}
                <h4>Salary:-<em>{{  data[job]["salary"]  }}</em></h4>
            {% endif %}
        </div>
        <div>
            <button onclick="window.location.href='{{ url_for('view.form') }}';" class="btn btn-primary btn-lg">Apply</button>
        </div>
    </section>
    <br>
{% endfor %}